website/apps/main/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

app_name = 'main'

urlpatterns = [
    url(r'^$',
        TemplateView.as_view(template_name="main/index.html"),
        name='index'),
    url(r'^download/?$',
        views.DownloadView.as_view(),
        name='download'),
    url(r'^download/(?P<pk>[^/]+)?$',
        views.DownloadReleaseView.as_view(),
        name='download-release'),
]

website/apps/user/urls.py
from django.conf.urls import url
from django.contrib.auth import views as django_auth_views
from django.contrib.auth.decorators import login_required

from . import views, views_remote
from .decorators import remote_login_required

app_name = 'user'


urlpatterns = [
    # changing visitor state
    url(r'^register/?$',
        views.RegisterView.as_view(),
        name='register'),
    url(r'^login/?$',
        views.LoginView.as_view(),
        name='login'),
    url(r'^logout/?$',
        django_auth_views.logout,
        name='logout'),
    # password reset
    url(r'^reset-password/?$',
        views.PasswordResetView.as_view(),
        name='password_reset'),
    url(r'^reset-password/done/?$',
        django_auth_views.password_reset_done,
        name='password_reset_done',
        kwargs={
            'template_name': 'user/reset-password-done.html',
        }),
    url(r'^reset-link/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        django_auth_views.password_reset_confirm,
        name='password_reset_confirm',
        kwargs={
            'template_name': 'user/reset-password-confirm.html',
            'post_reset_redirect': 'user:password_reset_complete',
        }),
    url(r'^reset-password/compete/?$',
        django_auth_views.password_reset_complete,
        name='password_reset_complete',
        kwargs={
            'template_name': 'user/reset-password-complete.html',
        }),

    # profile
    url(r'^profile/edit/?$',
        login_required(views.ProfileEditView.as_view()),
        name='edit-profile'),
    url(r'^profile/password-change/?$',
        login_required(django_auth_views.password_change),
        name='password_change',
        kwargs={
            'template_name': 'user/edit-password.html',
            'post_change_redirect': 'user:password_change_done',
        }),
    url(r'^profile/password-change/done/?$',
        login_required(django_auth_views.password_change_done),
        name='password_change_done',
        kwargs={
            'template_name': 'user/edit-password-done.html',
        }),

    # token validation
    url(r'^resend_validation_email/?$',
        login_required(views.ResendValidationEmailView.as_view()),
        name='resend-validation-email'),
    url(r'^validate_email/?$',
        views.ValidateTokenEmailView.as_view(),
        name='validate-email'),

    # for json api
    url(r'^login.json/?$',
        views_remote.RemoteLoginView.as_view(),
        name='login-json'),
    url(r'^me.json/?$',
        remote_login_required(views_remote.RemoteInfoUserView.as_view()),
        name='me-json'),
    url(r'^logout.json/?$',
        remote_login_required(views_remote.RemoteLogoutView.as_view()),
        name='logout-json'),

    url(r'^(?P<username>[a-zA-Z0-9-]+)/?$',
        views.ProfileView.as_view(),
        name='profile'),
]

website/core/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('main.urls')),
    url(r'^user/', include('user.urls')),
    url(r'^plugins/', include('plugins.urls')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
]

# debug
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

website/apps/plugins/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from markdown import markdown as compiler_markdown
from model_utils.models import TimeStampedModel
from taggit.managers import TaggableManager

from core.behaviors import Expirationable
from main.utils import generate_token


class Plugin(TimeStampedModel, models.Model):
    name = models.CharField(max_length=120)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    nb_download = models.IntegerField(default=0)
    nb_upvote = models.IntegerField(default=0)

    class Meta(object):
        ordering = ['nb_upvote', 'nb_download']

    @property
    def url(self):
        return reverse('plugins:detail', args=[self.author.username, self.name])

    @property
    def url_download(self):
        return reverse('plugins:download', args=[self.author.username, self.name])

    @property
    def last_release(self):
        return self.release_set.order_by('-created').first()

    def get_release(self, version=None):
        if version:
            return self.release_set.filter(version=version).first()
        return self.last_release

    def user_has_upvoted(self, user):
        if not user.is_authenticated():
            return False
        query = Upvote.objects.filter(plugin=self, user=user)
        return True if query.count() else False


def plugin_directory_path(instance, filename):
    filename = '{}.zip'.format(str(instance.version))
    return 'plugins/{}/{}/{}'.format(instance.plugin.author.username, instance.plugin.name, filename)


class Release(TimeStampedModel, models.Model):
    plugin = models.ForeignKey(Plugin, on_delete=models.CASCADE)
    version = models.IntegerField(default=0)
    archive = models.FileField(upload_to=plugin_directory_path)
    description = models.TextField(default='')
    readme = models.TextField(default='')
    readme_html = models.TextField(default='')
    tags = TaggableManager()
    checksum = models.CharField(max_length=64, default='')

    def __str__(self):
        return 'Release {} of {}/{}'.format(self.version,
            self.plugin.author.username, self.plugin.name)

    class Meta(object):
        ordering = ['-version']

    def set_readme(self, markdown):
        """
        Set the readme of the release.
        parameters in str
        Compile the markdown to html
        """
        self.readme = markdown.decode('utf8')
        self.readme_html = compiler_markdown(self.readme,
            extensions=['markdown.extensions.tables'])

    def add_tags(self, tags):
        """
        Add tags to the release
        tags is an array of tags
        """
        self.tags.add(*tags)

    def add_commands(self, commands):
        """
        Add commands to the release from the manifest file
        """
        self.plugincommand_set.all().delete()
        for command in commands:
            PluginCommand(
                release=self,
                plugin=self.plugin,
                name=command['name'],
                description=command.get('description', ''),
            ).save()


class PluginCommand(models.Model):
    release = models.ForeignKey(Release, on_delete=models.CASCADE)
    plugin = models.ForeignKey(Plugin, on_delete=models.CASCADE)
    name = models.CharField(max_length=120)
    description = models.TextField(default='')


class DownloadRelease(Expirationable, TimeStampedModel, models.Model):
    NB_DAY_EXPIRE = 0
    NB_MINUTE_EXPIRE = 5

    plugin = models.ForeignKey(Plugin, on_delete=models.CASCADE)
    release = models.ForeignKey(Release, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    token = models.CharField(max_length=50, default=generate_token)
    is_used = models.BooleanField(default=False)

    @property
    def url(self):
        return reverse('plugins:download-link',
            args=[self.token])


class UserPlugins(TimeStampedModel, models.Model):
    plugin = models.ForeignKey(Plugin, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    release = models.ForeignKey(Release, null=True, on_delete=models.SET_NULL)

    class Meta:
        unique_together = ('plugin', 'user')


class Upvote(TimeStampedModel, models.Model):
    plugin = models.ForeignKey(Plugin, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('plugin', 'user')

website/apps/user/models.py
from urllib.parse import quote

from django.db import models, transaction
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.urls import reverse
from model_utils.models import TimeStampedModel

from core.behaviors import Expirationable
from core.utils import send_email

from main.utils import generate_token


class ForbiddenUsername(models.Model):
    """
    List of username that can't be taken
    """
    username = models.CharField(max_length=50, unique=True)


class Device(Expirationable, TimeStampedModel, models.Model):
    """
    Represent a Daemon using the JSON API
    """
    NB_DAY_EXPIRE = 14  # expire after 2 weeks

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    token = models.CharField(max_length=50, default=generate_token, unique=True)


class Profile(TimeStampedModel, models.Model):
    """
    Extend the User model
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    validated = models.BooleanField(default=False)
    email_await_validation = models.EmailField(blank=True)


class EmailValidationToken(Expirationable, TimeStampedModel, models.Model):
    """
    Store the tokens for validating account
    """
    token = models.CharField(max_length=50, default=generate_token, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    consumed = models.BooleanField(default=False)

    def generate_validation_url(self, request):
        querystrings = "?email={}&token={}".format(quote(self.user.email), self.token)
        url = reverse('user:validate-email') + querystrings
        return request.build_absolute_uri(url)

    def is_valid(self, email):
        if self.consumed\
            or email != self.user.profile.email_await_validation\
            or self.is_expired():
            return False
        return True

    @transaction.atomic
    def consume(self):
        self.user.profile.validated = True
        self.user.profile.save()
        self.user.email = self.user.profile.email_await_validation
        self.consumed = True
        self.save()

    @staticmethod
    def create_and_send_validation_email(user, request):
        token = EmailValidationToken(user=user)
        token.save()
        send_email(
            'email/user_register.html',
            user.email,
            url_validation=token.generate_validation_url(request))


def profile_url(self):
    return reverse('user:profile', args=[self.username])

User.add_to_class('profile_url', profile_url)


@receiver(post_save, sender=User)
def after_user_save(sender, **kwargs):
    """
    Signal to create a profile model when a User is created
    """
    if kwargs['created']:
        Profile(user=kwargs['instance'],
            email_await_validation=kwargs['instance'].email).save()

website/apps/user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import password_validation

from . import validators


class RegisterForm(forms.ModelForm):
    email = forms.CharField(
        max_length=75,
        validators=[validators.emailUniqueValidator],
        required=True
    )
    username = forms.CharField(
        max_length=75,
        validators=[
            validators.UsernameValidator(),
            validators.blacklistUsername,
        ],
        required=True
    )
    password = forms.CharField(
        strip=False,
        widget=forms.PasswordInput,
        help_text=password_validation.password_validators_help_text_html(),
    )

    def clean_password(self):
        password = self.cleaned_data.get('password')
        self.instance.username = self.cleaned_data.get('username')
        password_validation.validate_password(password, self.instance)
        return password

    class Meta:
        model = User
        fields = ['email', 'username', 'password']


class EditProfileForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name']

website/apps/user/views.py
"""
Django view of the user app.
List of classes:
- RegisterView
- ProfileView
- ProfileEditView
- ValidateTokenEmailView
- ResendValidationEmailView
"""

from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import views as django_auth_views
from django.contrib.messages.views import SuccessMessageMixin
from django.db import transaction
from django.http import HttpResponseBadRequest
from django.shortcuts import redirect, get_object_or_404
from django.views.generic.edit import FormView, UpdateView
from django.views.generic import DetailView, TemplateView, View
from django.urls import reverse, reverse_lazy

from . import forms
from .mixins import LoginMixin
from .models import EmailValidationToken


class RegisterView(LoginMixin, SuccessMessageMixin, FormView):
    """
    This endpoint is a generic form view for the user registration.
    """

    template_name = "user/register.html"
    form_class = forms.RegisterForm
    success_message = 'Account created, welcome to the team !'

    @transaction.atomic
    def form_valid(self, form):
        """
        Create user after form validation.
        Send the validation token.
        Redirect to the home page.
        """
        data = form.cleaned_data
        user = User.objects.create_user(
            data['username'],
            data['email'],
            data['password']
        )
        EmailValidationToken.create_and_send_validation_email(user, self.request)
        self.login_user(user)
        return redirect('main:index')


class LoginView(SuccessMessageMixin, django_auth_views.LoginView):
    template_name = 'user/login.html'
    success_message = 'Welcome back !'


class PasswordResetView(SuccessMessageMixin, django_auth_views.PasswordResetView):
    template_name = 'user/reset-password.html'
    email_template_name = 'email/password_reset_email.html'
    success_url = reverse_lazy('user:password_reset_done')


class ProfileView(DetailView):
    """
    This endpoint allows one to see his profile.
    """
    template_name = "user/profile.html"
    model = User

    def get_object(self, queryset=None):
        return get_object_or_404(User, username=self.kwargs['username'])


class ProfileEditView(UpdateView):
    """
    This endpoint allows user to edit his profile.
    """
    template_name = "user/edit-profile.html"
    form_class = forms.EditProfileForm
    success_message = 'Profile updated'

    def get_success_url(self):
        return self.request.user.profile_url()

    def get_object(self, queryset=None):
        """Return the current user."""
        return self.request.user


class ValidateTokenEmailView(LoginMixin, View):
    """
    View validating token received by email.
    """

    def get(self, request, **kwargs):
        """
        Validate account from link sent by email.

        This endpoint tests if the token is in the database and
        if it's not expired, correspond to the correct user and
        if it's not consumed yet, then the user account will be
        validate after that.
        """
        try:
            token = EmailValidationToken.objects.get(token=request.GET['token'])
            if not token.is_valid(request.GET['email']):
                raise ValueError('invalid token')
            token.consume()
            if not request.user.is_authenticated:
                self.login_user(token.user)
            messages.success(request, 'Email validated')
            return redirect('main:index')
        except (EmailValidationToken.DoesNotExist, ValueError) as e:
            print(e)
            return HttpResponseBadRequest('Something went wrong with your token, please try again')


class ResendValidationEmailView(View):
    """
    This endpoint sends another email to validate the account
    of one person who didn't validated
    """

    def get(self, request, **kwargs):
        user = request.user
        if not user.profile.validated:
            EmailValidationToken.create_and_send_validation_email(user, request)
            messages.success(request, 'Validation email resent')
        return redirect(user.profile_url())

website/apps/user/templates/user/edit-password-done.html
{% extends "layout/main.html" %}

{% block content %}
    <p>Password successfully updated</p>
    <a href="{% url 'user:profile' user.username %}">Back to profile</a>
{% endblock %}

website/apps/user/templates/user/edit-password.html
{% extends "layout/main.html" %}

{% block content %}
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" />
    </form>
{% endblock %}

website/apps/user/templates/user/edit-profile.html
{% extends "layout/main.html" %}

{% load material_forms %}

{% block content %}
  <a href="{% url 'user:password_change' %}">Edit password</a>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        {% submit "Save" %}
    </form>
{% endblock %}

website/apps/user/templates/user/login.html
{% extends "layout/main.html" %}

{% load material_forms %}

{% block content %}
<div class="row">
  <div class="col s6 offset-s3 z-depth-2 grey darken-3">
    <h1>Login</h1>
    <form method="post" action="">
        {% csrf_token %}
        {% error_text form.non_field_errors %}
        {% input_text form.username "Username or email" %}
        {% input_text form.password %}
        {% submit "Sign in" %}
    </form>
    <br />
    <a href="{% url 'user:password_reset' %}">Forgotten password ?</a><br />
    <a href="{% url 'user:register' %}">Create account</a><br /><br />
  </div>
</div>
{% endblock %}

website/apps/user/templates/user/profile.html
{% extends "layout/main.html" %}

{% block content %}
  <h4>{{ object.username }}</h4>
  {% if object == request.user %}
    <p>First name: {{ object.first_name }} </p>
    <p>Last name: {{ object.last_name }} </p>
    <p>Email: {{ object.email }} </p>
    {% if not request.user.profile.validated %}
      You must validate your profile.<br />
      <a href="{% url 'user:resend-validation-email' %}">Click here to resend an email</a><br /><br />
    {% endif %}
    <a href="{% url 'user:edit-profile' %}">Edit my profile</a>
  {% endif %}
  <h4>Plugins</h4>
  <ul>
    {% for plugin in object.plugin_set.all %}
      <li><a href="{{ plugin.url }}">{{ plugin.name }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

website/apps/user/templates/user/register.html
{% extends "layout/main.html" %}

{% load material_forms %}

{% block content %}
<div class="row">
  <div class="col s8 offset-s2 z-depth-2 grey darken-3">
    <h1>Register</h1>
    <p>Register to the AVA project to download plugin and contribute to the ecosystem !</p>
    <form method="post" action="">
        {% csrf_token %}
        {% error_text form.non_field_errors %}
        {% input_text form.email %}
        {% input_text form.username %}
        {% input_text form.password %}
        {% submit "Create account" %}
    </form>
    <a href="{% url 'user:login' %}">Already member ?</a>
  </div>
</div>
{% endblock %}

website/apps/user/templates/user/reset-password-complete.html
{% extends "layout/main.html" %}

{% block content %}

  <h1>New password set !</h1>

  <p>Your password has been set. You may go ahead and log in now.</p>

  <p><a href="{{ login_url }}">Log in</a></p>
{% endblock %}

website/apps/user/templates/user/reset-password-confirm.html
{% extends "layout/main.html" %}

{% load material_forms %}

{% block content %}
<div class="row">
  <div class="col s8 offset-s2 z-depth-2 grey darken-3">
    {% if validlink %}
      <h1>Change password</h1>
      <p>Please enter your new password twice so we can verify you typed it in correctly.</p>
      <form method="post" action="">
          {% csrf_token %}
          {% error_text form.non_field_errors %}
          {% input_text form.new_password1 %}
          {% input_text form.new_password2 %}
          <center>{% submit "Change password" %}</center>
      </form>
      <br /><br />
    {% else %}
      <p>The password reset link was invalid, possibly because it has already been used.  Please request a new password reset <a href="{% url 'user:password_reset' %}">here</a>.</p>
    {% endif %}
  </div>
</div>
{% endblock %}

website/apps/user/templates/user/reset-password-done.html
{% extends "layout/main.html" %}

{% block content %}

  <h1>New password requested !</h1>

  <p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>

  <p>If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</p>

  <p>
    <a href="{% url 'main:index' %}">Home page</a>
  </p>

{% endblock %}

website/apps/user/templates/user/reset-password.html
{% extends "layout/main.html" %}

{% load material_forms %}

{% block content %}

<div class="row">
  <div class="col s8 offset-s2 z-depth-2 grey darken-3">
    <h1>Reset password</h1>
    <p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p>

    <form method="post">
        {% csrf_token %}
        {% input_text form.email %}
        {% submit "Reset my password" %}
    </form>
    <br />
    <a href="{% url 'user:login' %}">Log-in</a><br />
    <a href="{% url 'user:register' %}">Create account</a><br /><br />
  </div>
</div>

{% endblock %}