website/apps/plugins/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from . import views, views_remote
from user.decorators import remote_login_required

app_name = 'plugins'

urlpatterns = [
    url(r'^upload/?$',
        login_required(views.UploadPluginView.as_view()),
        name='upload'),
    url(r'^my-plugins/?$',
        remote_login_required(views_remote.MyPluginListView.as_view()),
        name='my-list'),
    url(r'^list/?$',
        views.PluginListView.as_view(),
        name='list'),
    url(r'^list.json/?$',
        views_remote.PluginListView.as_view(),
        name='list-json'),
    url(r'^download/(?P<token>[^/]+)/?$',
        remote_login_required(views_remote.PluginDownloadLinkView.as_view()),
        name='download-link'),
    url(r'^(?P<username>[^/]+)/(?P<plugin_name>[^/]+)/',
        include([
            url(r'^$',
                views.PluginDetailView.as_view(),
                name='detail'),
            url(r'^upvote/?$',
                login_required(views.PluginUpvoteView.as_view()),
                name='upvote'),
            url(r'^downvote/?$',
                login_required(views.PluginDownvoteView.as_view()),
                name='downvote'),
            url(r'^json/?$',
                views_remote.PluginDetailView.as_view(),
                name='detail-json'),
            url(r'^download/?$',
                remote_login_required(views_remote.PluginDownloadView.as_view()),
                name='download'),
            url(r'^download/(?P<version>[^/]+)/$',
                remote_login_required(views_remote.PluginDownloadView.as_view()),
                name='download-version'),
        ])
    ),
]

website/apps/user/urls.py
from django.conf.urls import url
from django.contrib.auth import views as django_auth_views
from django.contrib.auth.decorators import login_required

from . import views, views_remote
from .decorators import remote_login_required

app_name = 'user'


urlpatterns = [
    # changing visitor state
    url(r'^register/?$',
        views.RegisterView.as_view(),
        name='register'),
    url(r'^login/?$',
        views.LoginView.as_view(),
        name='login'),
    url(r'^logout/?$',
        django_auth_views.logout,
        name='logout'),
    # password reset
    url(r'^reset-password/?$',
        views.PasswordResetView.as_view(),
        name='password_reset'),
    url(r'^reset-password/done/?$',
        django_auth_views.password_reset_done,
        name='password_reset_done',
        kwargs={
            'template_name': 'user/reset-password-done.html',
        }),
    url(r'^reset-link/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        django_auth_views.password_reset_confirm,
        name='password_reset_confirm',
        kwargs={
            'template_name': 'user/reset-password-confirm.html',
            'post_reset_redirect': 'user:password_reset_complete',
        }),
    url(r'^reset-password/compete/?$',
        django_auth_views.password_reset_complete,
        name='password_reset_complete',
        kwargs={
            'template_name': 'user/reset-password-complete.html',
        }),

    # profile
    url(r'^profile/edit/?$',
        login_required(views.ProfileEditView.as_view()),
        name='edit-profile'),
    url(r'^profile/password-change/?$',
        login_required(django_auth_views.password_change),
        name='password_change',
        kwargs={
            'template_name': 'user/edit-password.html',
            'post_change_redirect': 'user:password_change_done',
        }),
    url(r'^profile/password-change/done/?$',
        login_required(django_auth_views.password_change_done),
        name='password_change_done',
        kwargs={
            'template_name': 'user/edit-password-done.html',
        }),

    # token validation
    url(r'^resend_validation_email/?$',
        login_required(views.ResendValidationEmailView.as_view()),
        name='resend-validation-email'),
    url(r'^validate_email/?$',
        views.ValidateTokenEmailView.as_view(),
        name='validate-email'),

    # for json api
    url(r'^login.json/?$',
        views_remote.RemoteLoginView.as_view(),
        name='login-json'),
    url(r'^me.json/?$',
        remote_login_required(views_remote.RemoteInfoUserView.as_view()),
        name='me-json'),
    url(r'^logout.json/?$',
        remote_login_required(views_remote.RemoteLogoutView.as_view()),
        name='logout-json'),

    url(r'^(?P<username>[a-zA-Z0-9-]+)/?$',
        views.ProfileView.as_view(),
        name='profile'),
]

website/core/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('main.urls')),
    url(r'^user/', include('user.urls')),
    url(r'^plugins/', include('plugins.urls')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
]

# debug
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

website/apps/plugins/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from markdown import markdown as compiler_markdown
from model_utils.models import TimeStampedModel
from taggit.managers import TaggableManager

from core.behaviors import Expirationable
from main.utils import generate_token


class Plugin(TimeStampedModel, models.Model):
    name = models.CharField(max_length=120)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    nb_download = models.IntegerField(default=0)
    nb_upvote = models.IntegerField(default=0)

    class Meta(object):
        ordering = ['nb_upvote', 'nb_download']

    @property
    def url(self):
        return reverse('plugins:detail', args=[self.author.username, self.name])

    @property
    def url_download(self):
        return reverse('plugins:download', args=[self.author.username, self.name])

    @property
    def last_release(self):
        return self.release_set.order_by('-created').first()

    def get_release(self, version=None):
        if version:
            return self.release_set.filter(version=version).first()
        return self.last_release

    def user_has_upvoted(self, user):
        if not user.is_authenticated():
            return False
        query = Upvote.objects.filter(plugin=self, user=user)
        return True if query.count() else False


def plugin_directory_path(instance, filename):
    filename = '{}.zip'.format(str(instance.version))
    return 'plugins/{}/{}/{}'.format(instance.plugin.author.username, instance.plugin.name, filename)


class Release(TimeStampedModel, models.Model):
    plugin = models.ForeignKey(Plugin, on_delete=models.CASCADE)
    version = models.IntegerField(default=0)
    archive = models.FileField(upload_to=plugin_directory_path)
    description = models.TextField(default='')
    readme = models.TextField(default='')
    readme_html = models.TextField(default='')
    tags = TaggableManager()
    checksum = models.CharField(max_length=64, default='')

    def __str__(self):
        return 'Release {} of {}/{}'.format(self.version,
            self.plugin.author.username, self.plugin.name)

    class Meta(object):
        ordering = ['-version']

    def set_readme(self, markdown):
        """
        Set the readme of the release.
        parameters in str
        Compile the markdown to html
        """
        self.readme = markdown.decode('utf8')
        self.readme_html = compiler_markdown(self.readme,
            extensions=['markdown.extensions.tables'])

    def add_tags(self, tags):
        """
        Add tags to the release
        tags is an array of tags
        """
        self.tags.add(*tags)

    def add_commands(self, commands):
        """
        Add commands to the release from the manifest file
        """
        self.plugincommand_set.all().delete()
        for command in commands:
            PluginCommand(
                release=self,
                plugin=self.plugin,
                name=command['name'],
                description=command.get('description', ''),
            ).save()


class PluginCommand(models.Model):
    release = models.ForeignKey(Release, on_delete=models.CASCADE)
    plugin = models.ForeignKey(Plugin, on_delete=models.CASCADE)
    name = models.CharField(max_length=120)
    description = models.TextField(default='')


class DownloadRelease(Expirationable, TimeStampedModel, models.Model):
    NB_DAY_EXPIRE = 0
    NB_MINUTE_EXPIRE = 5

    plugin = models.ForeignKey(Plugin, on_delete=models.CASCADE)
    release = models.ForeignKey(Release, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    token = models.CharField(max_length=50, default=generate_token)
    is_used = models.BooleanField(default=False)

    @property
    def url(self):
        return reverse('plugins:download-link',
            args=[self.token])


class UserPlugins(TimeStampedModel, models.Model):
    plugin = models.ForeignKey(Plugin, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    release = models.ForeignKey(Release, null=True, on_delete=models.SET_NULL)

    class Meta:
        unique_together = ('plugin', 'user')


class Upvote(TimeStampedModel, models.Model):
    plugin = models.ForeignKey(Plugin, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('plugin', 'user')

website/apps/plugins/forms.py
import json
import os
import avasdk

from zipfile import ZipFile, BadZipFile

from avasdk.plugins.manifest import validate_manifest
from avasdk.plugins.hasher import hash_plugin
from django import forms
from django.core.validators import ValidationError

from .validators import ZipArchiveValidator


class PluginArchiveField(forms.FileField):
    default_validators = [ZipArchiveValidator()]
    label = 'Plugin .zip'

    def get_prefix(self, archive):
        files = archive.namelist()
        return os.path.commonpath(files)

    def get_manifest(self, archive):
        try:
            with ZipFile(archive.temporary_file_path()) as plugin:
                prefix = self.get_prefix(plugin)
                prefix = prefix + '/' if len(prefix) else ''
                with plugin.open('{}manifest.json'.format(prefix)) as myfile:
                    manifest = json.loads(myfile.read())
                validate_manifest(manifest)
                return manifest
        except BadZipFile:
            raise ValidationError('Bad .zip format')
        except FileNotFoundError:
            raise ValidationError('Error with upload, please try again')
        except KeyError:
            raise ValidationError('No manifest.json found in archive')
        except json.JSONDecodeError:
            raise ValidationError('Error with manifest.json, bad Json Format')
        except avasdk.exceptions.ValidationError as e:
            raise ValidationError('Error in manifest.json ({})'.format(e))

    def get_readme(self, archive):
        try:
            with ZipFile(archive.temporary_file_path()) as plugin:
                prefix = self.get_prefix(plugin)
                prefix = prefix + '/' if len(prefix) else ''
                with plugin.open('{}/README.md'.format(prefix)) as myfile:
                    readme = myfile.read()
                return readme
        except FileNotFoundError:
            raise ValidationError('Error with upload, please try again')
        except KeyError:
            return None

    def clean(self, data, initial=None):
        f = super().clean(data, initial)
        manifest = self.get_manifest(f)
        readme = self.get_readme(f)
        return {
            'zipfile': f,
            'manifest': manifest,
            'readme': readme,
            'checksum': hash_plugin(f.temporary_file_path()),
        }


class UploadPluginForm(forms.Form):
    archive = PluginArchiveField()

website/apps/plugins/views.py
from django.db import transaction
from django.db.models import F, Q
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.http import Http404
from django.shortcuts import redirect
from django.views.generic import FormView, DetailView, ListView, View

from user.mixins import UserMustBeValidated
from . import forms, mixins
from .models import Plugin, Release, Upvote


class UploadPluginView(UserMustBeValidated, SuccessMessageMixin, FormView):
    template_name = 'plugins/upload.html'
    form_class = forms.UploadPluginForm
    success_message = 'Plugin uploaded successfully'

    def get_plugin(self, name):
        try:
            return Plugin.objects.get(name=name)
        except Plugin.DoesNotExist:
            return Plugin(name=name, author=self.request.user)

    @transaction.atomic
    def form_valid(self, form):
        data_plugin = form.cleaned_data['archive']
        self.plugin = self.get_plugin(data_plugin['manifest']['name'])
        self.plugin.save()
        nb_release = Release.objects.filter(plugin=self.plugin).count() + 1
        release = Release(
            plugin=self.plugin,
            checksum=data_plugin['checksum'],
            version=nb_release,
            description=data_plugin['manifest'].get('description', ''),
            archive=data_plugin['zipfile'])
        if data_plugin['readme']:
            release.set_readme(data_plugin['readme'])
        release.save()
        if 'tags' in data_plugin['manifest']:
            release.add_tags(data_plugin['manifest']['tags'])
        release.add_commands(data_plugin['manifest'].get('commands', []))
        return super().form_valid(form)

    def get_success_url(self):
        return self.plugin.url


class PluginListView(ListView):
    model = Plugin
    template_name = 'plugins/list.html'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        kwargs['search_string'] = self.request.GET.get('search', '')
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        search_on_text = self.request.GET.get('search', None)
        if not search_on_text:
            return queryset
        search = Q(name__icontains=search_on_text)
        search |= Q(author__username__startswith=search_on_text)
        return queryset.filter(search)


class PluginDetailView(mixins.PluginDetailMixin, DetailView):
    template_name = 'plugins/detail.html'

    def get_release(self):
        return self.object.get_release(self.request.GET.get('version', None))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_has_upvoted'] = self.object.user_has_upvoted(self.request.user)
        context['release'] = self.get_release()
        if not context['release']:
            raise Http404('Can\'t find this version')
        return context


class PluginUpvoteView(UserMustBeValidated, mixins.PluginDetailMixin, View):

    @transaction.atomic
    def get(self, request, *args, **kwargs):
        plugin = self.get_object()
        params = {'user': request.user, 'plugin': plugin}
        if Upvote.objects.filter(**params).count() == 0:
            Upvote.objects.create(**params)
            plugin.nb_upvote = F('nb_upvote') + 1
            plugin.save(update_fields=['nb_upvote'])
            messages.success(request, 'Upvote sent')
        return redirect(plugin.url)


class PluginDownvoteView(UserMustBeValidated, mixins.PluginDetailMixin, View):

    @transaction.atomic
    def get(self, request, *args, **kwargs):
        plugin = self.get_object()
        if Upvote.objects.filter(user=request.user, plugin=plugin).delete()[0] == 1:
            plugin.nb_upvote = F('nb_upvote') - 1
            plugin.save(update_fields=['nb_upvote'])
            messages.success(request, 'Upvote removed')
        return redirect(plugin.url)

website/apps/plugins/templates/plugins/detail.html
{% extends "layout/main.html" %}

{% load comments %}

{% block content %}
  <a href="{% url "plugins:list" %}">Back to plugin list</a>
  <h1>Plugin detail : {{ plugin.name }}</h1>
  <p>by <a href="{{ plugin.author.profile_url }}">{{ plugin.author.username }}</a></p>
  <p>
    {{ release.description }}
  </p>
  <hr />
  <h2>Install command</h2>
  <pre>
avacli install {{ plugin.author.username }} {{ plugin.name }}
  </pre>
  <hr />
  <p>Number of download : {{ plugin.nb_download }}</p>
  <p>
    Number of upvote : {{ plugin.nb_upvote }}
    {% if user.is_authenticated %}
      {% if user_has_upvoted %}
        <a href="{% url 'plugins:downvote' username=plugin.author.username plugin_name=plugin.name %}">Downvote</a>
      {% else %}
        <a href="{% url 'plugins:upvote' username=plugin.author.username plugin_name=plugin.name %}">Upvote</a>
      {% endif %}
    {% endif %}
  </p>
  <div>
    {{ release.readme_html|safe }}
  </div>
  <h3>List of releases :</h3>
  <ul>
    {% for release in plugin.release_set.all %}
      <li><a href="?version={{ release.version }}">{{ release.version }}</a></li>
    {% endfor %}
  </ul>
  <h3>Tags:</h3>
  <ul>
    {% for tag in release.tags.names %}
      <li>{{ tag }}</li>
    {% endfor %}
  </ul>
  <h3>command:</h3>
  <div>
    {% for command in release.plugincommand_set.all %}
    name : {{ command.name }}<br />
    description : {{ command.description }}<br />
    {% endfor %}
  </div>
  <h3>Comments :</h3>
  {% if user.is_authenticated %}
      {% get_comment_form for plugin as form %}
      <form action="{% comment_form_target %}" method="POST">
      {% csrf_token %}
      {{ form.comment }}
      {{ form.content_type }}
      {{ form.object_pk }}
      {{ form.timestamp }}
      {{ form.security_hash }}
      <input type="hidden" name="next" value="{{ plugin.url }}" />
      <input type="submit" value="Add comment" id="id_submit" />
      </form>
  {% else %}
      <p>Please <a href="{% url 'user:login' %}">log in</a> to leave a comment.</p>
  {% endif %}

  <ul>
    {% get_comment_list for plugin as comment_list %}
    {% for comment in comment_list %}
      <li>{{ comment }}</li>
    {% endfor %}
  </ul>
{% endblock %}

website/apps/plugins/templates/plugins/list.html
{% extends "layout/main.html" %}

{% load material_forms %}

{% block content %}
  <div class="row">
    <h1>Plugins list</h1>
    <p>
      Here you can find all the plugins the community made. You can click on it to get a more detailed view of what the plugin does.
    </p>
    <form method="get" action="" class="col s12">
      <div class="input-field">
        <input id="search" type="search" value="{{ search_string }}" name="search"  required>
        <label for="search">Search</label>
      </div>
      {% submit "Search" %}
    </form>
    <br /><br />
    <div>
      {% for plugin in object_list %}
        <div>
          <a href="{{ plugin.url }}">{{ plugin.name }}</a>
          <p>{{ plugin.last_release.description }}</p>
          <span>{{ plugin.nb_upvote }} Upvotes</span>
          <p>by <a href="{{ plugin.author.profile_url }}">{{ plugin.author.username }}</a></p>
        </div>
        <hr />
      {% empty %}
        <p>No result</p>
      {% endfor %}
    </div>

    {% if is_paginated %}
      <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
            {% endif %}
        </span>
      </div>
    {% endif %}
  </div>
{% endblock %}

website/apps/plugins/templates/plugins/upload.html
{% extends "layout/main.html" %}

{% block content %}
    <form method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" />
    </form>
{% endblock %}